### ISSUE TITLE
Release fails with IllegalStateException

### ISSUE THREAD

**Issue by francisdb** [swoval/MacOSXWatchService#42]
watcher `1.2.0`
sbt `1.1.0`

I tried building a release and just after packaging I get this error for every sub-project. I wonder why this plugin is active when not using `~`

```
sbt release
```

no context visible on what exactly fails (exception message)

```
[error] java.lang.IllegalStateException
[error] 	at com.swoval.files.apple.FileEventsApi.createStream(FileEventsApi.java:50)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:26)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:23)
[error] 	at com.swoval.files.FileCacheImpl.$anonfun$register$2(FileCache.scala:35)
[error] 	at com.swoval.files.FileCacheImpl.$anonfun$register$2$adapted(FileCache.scala:35)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at com.swoval.files.FileCacheImpl.register(FileCache.scala:35)
[error] 	at com.swoval.files.FileCacheImpl.list(FileCache.scala:25)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$3(MacOSXWatchServicePlugin.scala:48)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$1(MacOSXWatchServicePlugin.scala:58)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eatkins** [comment]
I’m out of town until Friday so I can’t investigate right now, but by default the plugin overrides the sbt source files list so it is in effect even when ~ is not used. This can be disabled by setting useDefaultSourceList = true. I’m not sure if this will fix your issue, but it might work as a temporary workaround. It will make compiling after source changes slower in large projects because sbt by default always lists the source directories with system calls, which is slow when there are many files/directories (close to 1 second to ls 5000 files on my mac).

**Comment by francisdb** [comment]
No hurry, I just disable the (global) plugin when doing releases.

**Comment by francisdb** [comment]
Seeing the same when doing a cross-scala compile

```
+test
[info] Setting Scala version to 2.12.4 on 3 projects.
[info] Reapplying settings...
[info] Set current project to metrics (in build file:/Users/francisdb/workspace/jvm-metrics/)
[error] java.lang.IllegalStateException
[error] 	at com.swoval.files.apple.FileEventsApi.createStream(FileEventsApi.java:50)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:26)
[error] 	at com.swoval.files.AppleDirectoryWatcher.register(AppleDirectoryWatcher.scala:23)
[error] 	at com.swoval.files.FileCacheImpl.$anonfun$register$2(FileCache.scala:35)
[error] 	at com.swoval.files.FileCacheImpl.$anonfun$register$2$adapted(FileCache.scala:35)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at com.swoval.files.FileCacheImpl.register(FileCache.scala:35)
[error] 	at com.swoval.files.FileCacheImpl.list(FileCache.scala:25)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$3(MacOSXWatchServicePlugin.scala:48)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.swoval.watchservice.MacOSXWatchServicePlugin$.$anonfun$cachedSourcesFor$1(MacOSXWatchServicePlugin.scala:58)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by francisdb** [comment]
Re-enabled the plugin using `1.2.1`, will let you know in case there still are issues
