### ISSUE TITLE
NullPointerException while obtaining files to watch

### ISSUE THREAD

**Issue by francisdb** [swoval/MacOSXWatchService#5]
I got this after adding the 1.0.3 plugin to our project and doing a `clean` followed by `~test:compile`

However this does not crash sbt, running another `~test:compile` works without issues and reacts fast to changes

sbt `1.0.4`
jdk `1.8.0_152-b16`

```
[error] Error occurred obtaining files to watch.  Terminating continuous execution...
[error] java.lang.NullPointerException
[error] 	at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:198)
[error] 	at sun.nio.fs.UnixPath.resolve(UnixPath.java:397)
[error] 	at sun.nio.fs.UnixPath.resolve(UnixPath.java:43)
[error] 	at sbt.internal.io.SourceModificationWatch$.expandEvent(SourceModificationWatch.scala:70)
[error] 	at sbt.internal.io.SourceModificationWatch$.$anonfun$watch$1(SourceModificationWatch.scala:28)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.immutable.List.map(List.scala:295)
[error] 	at sbt.internal.io.SourceModificationWatch$.watch(SourceModificationWatch.scala:28)
[error] 	at sbt.Watched$.liftedTree1$1(Watched.scala:102)
[error] 	at sbt.Watched$.executeContinuously(Watched.scala:100)
[error] 	at sbt.BasicCommands$.$anonfun$continuous$2(BasicCommands.scala:215)
[error] 	at sbt.CommandUtil$.withAttribute(CommandUtil.scala:42)
[error] 	at sbt.BasicCommands$.$anonfun$continuous$1(BasicCommands.scala:213)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by eatkins** [comment]
Yeah, I think I know what is causing that. I should have an updated release today that will fix it.

**Comment by eatkins** [comment]
Would you try v1.1.0 and let me know if the problem is still occurring?

**Comment by francisdb** [comment]
Previous error is gone but I now see the logs below.
Also change detection seems to be non-working.

```
2017-11-30 20:35 java[15435] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-30 20:35 java[15435] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-30 20:35 java[15435] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-30 20:35 java[15435] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-30 20:35 java[15435] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-30 20:35 java[15435] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
...
```

**Comment by eatkins** [comment]
Interesting. I don't see this on my machine, but I'm testing on a small project. My guess is that it's related to the number of files being watched. I'll investigate further and try to reproduce.

**Comment by francisdb** [comment]
1.0.3 was better in that it just logs that nullpointer on startup but works correctly after that

**Comment by eatkins** [comment]
I have a repro, so hopefully it won't be too bad to work through.

**Comment by eatkins** [comment]
Can you try version 1.1.1-007deffa0f24bc99b4c60cbf93bfefc7332a6290 ? I don't want to keep making a ton of releases, but this version resolves those errors for me in a project with many files.

```
resolvers += Resolver.bintrayIvyRepo("swoval", "sbt-plugins")
addSbtPlugin("com.swoval" %% "sbt-mac-watch-service" % "1.1.1-007deffa0f24bc99b4c60cbf93bfefc7332a6290")
```

**Comment by francisdb** [comment]
👌 no more logs / errors and fast triggers
